name: Keep Render Alive

on:
  schedule:
    - cron: "*/10 * * * *"
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest

    steps:
      - name: Ping Render Health Check
        run: curl -fsS https://magicpin-ai-challenge-67jm.onrender.com/v1/healthz
